global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'your_app'
    static_configs:
      - targets: ['localhost:8080']  # Substituir para o endereço da aplicação

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']